-- SQL-структура базы RecipeKeeper для SQLite.
-- Файл нужен, чтобы база была описана отдельно от интерфейса приложения.

CREATE TABLE IF NOT EXISTS Users (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Email TEXT NOT NULL UNIQUE,
    PasswordHash TEXT NOT NULL,
    Role TEXT NOT NULL DEFAULT 'User',
    Status INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Categories (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Recipes (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    Description TEXT NOT NULL,
    Instructions TEXT NOT NULL,
    CookingTime INTEGER NOT NULL,
    Servings INTEGER NOT NULL,
    CategoryId INTEGER NOT NULL,
    UserId INTEGER NULL,
    ImageUrl TEXT NOT NULL DEFAULT '',
    Difficulty TEXT NOT NULL DEFAULT 'Лёгкий',
    FOREIGN KEY (CategoryId) REFERENCES Categories(Id),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE IF NOT EXISTS Ingredients (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    RecipeId INTEGER NOT NULL,
    Name TEXT NOT NULL,
    Amount TEXT NULL,
    FOREIGN KEY (RecipeId) REFERENCES Recipes(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Products (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    Name TEXT NOT NULL,
    Quantity TEXT NULL,
    ExpiresAt TEXT NULL,
    Unit TEXT NOT NULL DEFAULT '',
    Category TEXT NOT NULL DEFAULT '',
    Note TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Favorites (
    UserId INTEGER NOT NULL,
    RecipeId INTEGER NOT NULL,
    CreatedAt TEXT NOT NULL,
    PRIMARY KEY (UserId, RecipeId),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (RecipeId) REFERENCES Recipes(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RecipeViews (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    RecipeId INTEGER NOT NULL,
    ViewedAt TEXT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (RecipeId) REFERENCES Recipes(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MealPlan (
    UserId INTEGER NOT NULL,
    DayName TEXT NOT NULL,
    RecipeId INTEGER NOT NULL,
    PRIMARY KEY (UserId, DayName),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (RecipeId) REFERENCES Recipes(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ShoppingItems (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    Name TEXT NOT NULL,
    Quantity TEXT NULL,
    IsBought INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RecipeStats (
    RecipeId INTEGER PRIMARY KEY,
    CookCount INTEGER NOT NULL DEFAULT 0,
    Rating INTEGER NOT NULL DEFAULT 5,
    FOREIGN KEY (RecipeId) REFERENCES Recipes(Id) ON DELETE CASCADE
);
